name: FungiClef
channels:
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - pip:
    - azure-storage-blob 
    - azure-identity
    - notebook
    - numpy
    - matplotlib
    - scipy
    - scikit-image
    - ortools
    - opencv-contrib-python
    - torch
    - torchvision
    - scikit-learn
